- name: "update packages."
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "install dependencies."
  become: true
  apt: 
    name: [ "unzip"]
    state: latest
    update_cache: true

- name: "install nodejs."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2."
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present