---
- name: Copy files from backend
  become: true
  copy:
    src: /root/project/backend.zip
    dest: /tmp

- name: "unzip folder."
  become: true
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start